blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('feeds/', LatestPostFeed(), name='post_feed'),
    path('<category_slug>/', views.post_list, name='post_list_by_category'),
    path(r'<int:year>/<int:month>/<int:day>/' r'<str:post>/', views.post_detail, name='post_detail')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset() \
            .filter(status='published')

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category', args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def save(self, *args, **kwargs):
        self.slug = self.name
        super().save(*args, **kwargs)


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    image = models.ImageField(default=None, upload_to="media", height_field=None, width_field=None, max_length=100, null=True, blank=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return reverse('blog:post_detail', kwargs={'post_id': self.pk})
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    approved_comment = models.BooleanField(default=False)
    parent = models.ForeignKey('self', null=True, related_name='replies', on_delete=models.CASCADE )


    def approve(self):
        self.approved_comment = True
        self.save()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

class Subscription(models.Model):
    your_email = models.EmailField(blank=True)


    def __str__(self):
        return self.your_email

blog/forms.py
from django import forms
from .models import Comment, Subscription

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')



class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['your_email', ]



blog/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, SubscriptionForm
from django.core.mail import send_mail


def post_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    blogs = Post.published.all().order_by("-publish")
    form = SubscriptionForm(request.POST or None,
                            request.FILES or None)  # we embedded a form where users can input their emails to subcribe to our newsletter
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Thank you for subscribing")
    else:
        form = SubscriptionForm
    query = request.GET.get("q")
    if query:
        blogs = blogs.filter(Q(title__icontains=query)|
                                         Q(body__icontains=query)

                                         ).distinct()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        blogs = blogs.filter(category=category)
    paginator = Paginator(blogs, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    template = 'blog/post/list.html'
    context = {
        'posts': posts,
        'page': page,
        'form': form,
        'category': category, 
        'categories': categories,
    }
    return render(request, template, context )


def post_detail(request, year, month, day, post, category_slug=None):
    category = None
    categories = Category.objects.all()
    post = get_object_or_404(Post, slug=post,
            status='published',
            publish__year=year,
            publish__month=month,
            publish__day=day)
    comments = post.comments.filter(approved_comment=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.save()
        messages.add_message(request, messages.INFO, 'Your Comment has been submitted for review. It will be added shortly')
    else:
        comment_form = CommentForm
    template = 'blog/post/detail.html',
    context ={
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
         'category': category, 
        'categories': categories,}
    return render(request, template, context)


"""def post_share(request, post_id):
    #Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        #Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            from_email = settings.EMAIL_HOST_USER
            to_email = [from_email, 'youremail@mail.com']

            # send_mail(subject, message, 'admin@myblog.com',
            #           [cd['to']])
            send_mail(
                subject, message, from_email, to_email, fail_silently=False,
            )

            sent = True
    else:
        form = EmailPostForm()
    template = 'blog/post/share.html'
    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }
    return render(request, template, context)"""





templates/blog/post/add_comment_to_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
    {% endfor %}
</ul>
{% endif %}


{% else %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endif %}
{% endblock %}}

templates/blog/post/detail.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}{{ post.title }}{%endblock %}
{% block content %}
<div>
	<h1 class="font-weight-bold text-dark text-center">{{ post.title }}</h1>
	<p class="text-primary text-center mb-5">
		Published {{ post.publish }} by {{ post.author }}
	</p>
	<div class="row">
		<div class="col-md-5 col-sm-12">
			<img src="{{post.image.url}}" width="100%" height="100%"  class="img-responsive"/><br />
		</div>
		<div class="col-md-7 col-sm-12">
			<p>{{ post.body|linebreaks }}</p>
		</div>
	</div>
	<p><a href="{% url 'blog:post_list' %}">Back to blog page...</a></p><hr>

<div class="mt-3">
	{% with comments.count as total_comments %}
	<h5 class="text-center text-primary">
		{{ total_comments }} comment{{ total_comments|pluralize }}
	</h5>
	{% endwith %} {% for comment in comments %}
	<div class="my-4 card shadow-lg">
		<div class="d-flex justify-content-between p-3">
			<!-- <span>Comment {{ forloop.counter }} by <mark>{{ comment.name }}</mark></span> -->
			<span><mark>{{ comment.name }}</mark></span>
			<span>{{ comment.created }}</span>
		</div><hr/>
		<div class="px-3">
			{{ comment.body|linebreaks }}
		</div>
	</div>
	{% empty %}
	<p>There are no comments yet.</p>
	{% endfor %} {% if new_comment %}
	<h2>Your comment has been added.</h2>
	{% else %}
	<h5 class="text-center">Add a new comment</h5>
	<small class="text-danger">Please note that your comment will be reviewed before it is displayed for others to see.</small>
	<form action="." method="post">
		<p>
			<label for="id_name">
				Name:
			</label>
			<input
				type="text"
				name="name"
				maxlength="80"
				required=""
				id="id_name"
				class="form-control"
				placeholder="Enter your name here"
			/>
		</p>
		<p>
			<label for="id_body">
				Body:
			</label>
			<textarea
				name="body"
				rows="10"
				cols="50%"
				class="form-control"
				placeholder="Enter your comment here"
				id="id_body"
			></textarea>
		</p>
		<input
			type="hidden"
			name="csrfmiddlewaretoken"
			value="tda9nzLEl8fyXyP8MlFSyq1AL27EGUcoavs1pX3gHF0YrbicSKANYHpIdOdrNfaQ"
		/>
		{% csrf_token %}
		<p>
			<input type="submit" class="btn btn-info" value="Submit Comment" />
		</p>
	</form>
	{% endif %}
</div>
</div>
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "base.html" %} 
{% load static %} 
{% block title%}DaddyRufus{%endblock %}
 {% block content %} 
 {% for post in posts %}
<!-- Blog Post -->
<div class="card mb-4 text-justify shadow-lg rounded">
	<!-- <img class="card-img-top" src="{{post.image.url}}" alt="image loading..." /> -->
	<div class="card-body">
		<h3 class="card-title text-capitalize">
			<a href="{{ post.get_absolute_url }}" style="color: black !important; font-weight: bolder !important;">{{ post.title }}</a>
		</h3>
		<p class="mt-2">
			Posted on {{ post.publish }} by
		<a href="#">{{ post.author }}</a>
		</p>
		<h6 class="card-title text-capitalize" style="color: brown !important; font-weight: bolder !important;">
		 Category: {{ post.category }}
		</h6>
		<p class="">{{ post.body|truncatewords:50|linebreaks }}</p>
		<div>
		<a href="{{ post.get_absolute_url }}" class="text-primary"
			>Read More &rarr;</a
		>
		
		</div>
	</div>
	
</div>
{% endfor %} {% include "pagination.html" with page=posts %} {% endblock %}