blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('feeds/', LatestPostFeed(), name='post_feed'),
    path('<category_slug>/', views.post_list, name='post_list_by_category'),
    path(r'<int:year>/<int:month>/<int:day>/' r'<str:post>/', views.post_detail, name='post_detail')
]

contact/urls.py
from django.urls import path, include
from contact import views


app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact'),

]

templates/base.html
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %} DaddyRufusBlog {% endblock %}</title>
    {% load blog_tags %}
	{% load static %}
    {% load crispy_forms_tags %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
	<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css"/>
</head>
<body>

{% block header %}
    {% include 'navbar.html' %}
{% endblock %}

{% block body %}
{% block background %}
    <div class="background-image">
        <div class="text-center message sr-only-focusable">
            <h6>A Christain Blog to help draw back our focus to <span  style="font-size: 60px;">Jesus Christ</span></h6>
            <p>Welcome. We have <span class="text-danger" style="font-size: 60px;">{% total_posts %}</span> posts so far...</p>
        </div>
    </div>
{% endblock background %}
    <div class="container mt-5 pt-4 ">
        <!-- {% block intro %} <h2 class="my-4 text-center text-dark"><em>WELCOME! I STRONGLY BELIEVE YOU WILL LEARN SOMETHING NEW BEFORE YOU LEAVE</em></h2><hr>{% endblock %} -->
        <div class="row">
			<div class="col-md-12 col-sm-12">
                {% block content %}
				{% endblock %}
			</div>
            <div class="row text-center">
                <div class="col-sm-12 ">
                        {% block message %}
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <h4 class="text-primary text-uppercase"><li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></h4>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        {% endblock %}
                </div>
               
            </div>
        </div> 
    </div>





        </div>
      </div>
      <!-- /.row -->

    </div>
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/footer.html
{% load blog_tags %}
<footer id="footer">
<div class="container">
    <div class="row">
        <div class="col-md-4 col-sm-12 my-3">
          <h4 class="mb-2 text-uppercase my-2">Latest posts</h4>
         {% show_latest_posts 3 %}
        </div>
        <div class="col-md-4 col-sm-12 my-3">
          <h4 class="text-uppercase my-2">Most commented posts</h4>
          {% get_most_commented_posts as most_commented_posts %}
          {% for post in most_commented_posts %}
          <i class="fa fa-check text-danger"></i> <span>
                  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </span><br>
          {% endfor %}         
        </div>
        <div class="col-md-4 col-sm-12 my-3">
          <div class="col-sm-12 text-center mb-5">
            <h6 class="text-uppercase my-2">Be the first to know when we make a new post</h6>
            <form method="POST" action="" enctype="multipart/form-data">
                <div class="col-md-12">
                    <input  type="email" class="col-md-12 form-control" name="your_email" id="newsletter_email"  placeholder="Your email" required="required" data-error="Valid email is required."></p>
                    {% csrf_token %}
                    <button id="newsletter_submit" type="submit"  value="Submit" class="form-control bg-dark text-light">subscribe</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>
</footer>

templates/navbar.html
    <nav class="navbar navbar-expand-lg navbar bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand text-light" href="#">Daddy Rufus</a>
        <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
                        
              <form method="GET" action="">
                <input class="form-control" type="text" name="q" placeholder="Enter Keyword" value="{{ request.GET.q }}" width="100%"/>
              </form>         
            
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'blog:post_list' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="#">About Author</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'contact:contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <div class="btn-group">
                <span style="padding: 0px 0px;" class="btn text-light dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                      Categories
              </span>
             
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                  {% for c in categories %}
                      <a href="{{ c.get_absolute_url }}" class="dropdown-item" {% if category.slug == c.slug %}{% endif %}> {{ c.name }}</a>                     
                  {% endfor %}
                </div>
                
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

templates/pagination.html
<div class="pagination my-5">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}{% if request.Get.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
         {% endif %}
     <span class="current">
         {% block background %}{% endblock %}
         Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
             <a href="?page={{ page.next_page_number }}{% if request.Get.q %}
            &q={{ request.GET.q }}{% endif %}">Next</a>
        {% endif %}
    </span>
</div>